name: Schedule Login Test with Allure Report

# Runs every day at 11:30 AM IST
# 11:30 AM IST - 5 hours 30 minutes= 6:00 AM UTC


on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
      
      - name: Clean Allure Results
        run: rm -rf allure-results
        
      - name: Run LoginTest
        run: mvn test -Dtest=LoginTest
      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

        
